#!/usr/bin/env php
<?php
/**
 * Commands for composer.
 * AYUCO for bower assets installation.
 *
 * @author Alejandro Mostajo
 * @license MIT
 * @package Amostajo\Wordpress\PostPickerAddon
 * @version 1.0
 */
if ( empty( $argv ) || count($argv) <= 1 ) { print( 'No command given.' ); die; }

$function = $argv[1];

if ( ! function_exists( $function ) ) { print( $function . ' command not found.' ); die; }

unset( $argv[0] );
unset( $argv[1] );

call_user_func_array( $function, $argv );

/**
 * BOWER INSTALL
 * @since 1.0
 *
 * @param int $echofull Indicates if needs to echo all commands flow.
 */
function bowerInstall($echofull = 0)
{
    $origin = getcwd();
    ob_start();
    echo 'Installing bower assets...' . "\n";
    chdir( __DIR__ );
    if ($echofull)
        echo 'Moved to: ' . "\n" . getcwd() . "\n";
    ob_flush();
    passthru( 'bower install', $e );
    if ($e)
        echo json_encode( $e );
    ob_flush();
    chdir($origin);
    if ($echofull)
        echo 'Moved back to: ' . "\n" . getcwd() . "\n";
    ob_end_flush();
}

/**
 * BOWER UPDATE
 * @since 1.0
 *
 * @param int $echofull Indicates if needs to echo all commands flow.
 */
function bowerUpdate($echofull = 0)
{
    $origin = getcwd();
    ob_start();
    echo 'Updating bower assets...' . "\n";
    chdir( __DIR__ );
    if ($echofull)
        echo 'Moved to: ' . "\n" . getcwd() . "\n";
    ob_flush();
    passthru( 'bower update', $e );
    if ($e)
        echo json_encode( $e );
    ob_flush();
    chdir($origin);
    if ($echofull)
        echo 'Moved back to: ' . "\n" . getcwd() . "\n";
    ob_end_flush();
}
